# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 21:55
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_Of_Post', models.TimeField()),
                ('Date_Of_Start', models.DateTimeField()),
                ('Date_Of_End', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver_ID', models.IntegerField(verbose_name=app.models.General_User)),
                ('Time_Of_Post', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='General_User',
            fields=[
                ('General_User_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('General_User_Name', models.CharField(max_length=10)),
                ('General_User_Password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Premium_User',
            fields=[
                ('Premium_User_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Premium_User_Name', models.CharField(max_length=10)),
                ('Premium_User_Password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Zip', models.CharField(max_length=11)),
                ('Phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Premium_User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Premium_User')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement_list',
            name='Premium_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Premium_User'),
        ),
        migrations.AddField(
            model_name='advertisement_list',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='Premium_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Premium_User'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
