# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premium_user',
            old_name='Address',
            new_name='Store_Address',
        ),
        migrations.RenameField(
            model_name='premium_user',
            old_name='Phone',
            new_name='Store_Name',
        ),
        migrations.RenameField(
            model_name='premium_user',
            old_name='Zip',
            new_name='Store_Zip',
        ),
        migrations.AddField(
            model_name='premium_user',
            name='Store_Phone',
            field=models.CharField(default=5555555555, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='general_user',
            name='General_User_Password',
            field=models.BinaryField(),
        ),
    ]
