# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161103_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general_user',
            name='General_User_Password',
        ),
        migrations.AlterField(
            model_name='premium_user',
            name='Premium_User_Password',
            field=models.BinaryField(),
        ),
    ]
