# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161108_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='Premium_User_ID',
            new_name='Premium_User',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='Product_ID',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='advertisement_list',
            old_name='Premium_User_ID',
            new_name='Premium_User',
        ),
        migrations.RenameField(
            model_name='advertisement_list',
            old_name='Product_ID',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='advertisement_list',
            old_name='Receiver_ID',
            new_name='Receiver',
        ),
        migrations.RenameField(
            model_name='product_list',
            old_name='Premium_User_ID',
            new_name='Premium_User',
        ),
        migrations.RenameField(
            model_name='product_list',
            old_name='Product_ID',
            new_name='Product',
        ),
        migrations.RemoveField(
            model_name='general_user',
            name='General_User_ID',
        ),
        migrations.RemoveField(
            model_name='premium_user',
            name='Premium_User_ID',
        ),
        migrations.RemoveField(
            model_name='premium_user',
            name='Premium_User_Password',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_ID',
        ),
        migrations.AddField(
            model_name='general_user',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premium_user',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
