# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161110_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='Date_Of_End',
            new_name='date_Of_End',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='Date_Of_Start',
            new_name='date_Of_Start',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='Premium_User',
            new_name='premium_User',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='Time_Of_Post',
            new_name='time_Of_Post',
        ),
        migrations.RenameField(
            model_name='advertisement_list',
            old_name='Premium_User',
            new_name='premium_User',
        ),
        migrations.RenameField(
            model_name='advertisement_list',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='advertisement_list',
            old_name='Receiver',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='advertisement_list',
            old_name='Time_Of_Post',
            new_name='time_Of_Post',
        ),
        migrations.RenameField(
            model_name='product_list',
            old_name='Premium_User',
            new_name='premium_User',
        ),
        migrations.RenameField(
            model_name='product_list',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product_list',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product_list',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertisement_concent',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
