# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20161110_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general_user',
            name='General_User_Name',
        ),
        migrations.RemoveField(
            model_name='premium_user',
            name='Premium_User_Name',
        ),
        migrations.AddField(
            model_name='general_user',
            name='general_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premium_user',
            name='premium_User',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
