# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161112_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general_user',
            name='general_user',
        ),
        migrations.RemoveField(
            model_name='premium_user',
            name='premium_User',
        ),
        migrations.AddField(
            model_name='general_user',
            name='General_User_Name',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premium_user',
            name='Premium_User_Name',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
