# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161112_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='premium_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
