# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161124_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement_list',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_concent',
            field=models.BinaryField(),
        ),
    ]
