# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161125_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='premium_user',
        ),
        migrations.RemoveField(
            model_name='advertisement_list',
            name='product',
        ),
        migrations.RemoveField(
            model_name='advertisement_list',
            name='time_of_post',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='mime_Type',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement_list',
            name='advertisement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Advertisement'),
            preserve_default=False,
        ),
    ]
