# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20161125_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='date_of_end',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='date_of_start',
        ),
    ]
