# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20161125_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_user',
            name='General_User_Name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='premium_user',
            name='Premium_User_Name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
